! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2025-2026, Lawrence Livermore National Security,
! University of Maryland Baltimore County, and the SUNDIALS contributors.
! Copyright (c) 2013-2025, Lawrence Livermore National Security
! and Southern Methodist University.
! Copyright (c) 2002-2013, Lawrence Livermore National Security.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunnonlinsol_auto_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 ! enum SUNNonlinSolAutoType
 enum, bind(c)
  enumerator :: SUNNONLINSOL_AUTO_FIXEDPOINT = 0
  enumerator :: SUNNONLINSOL_AUTO_NEWTON = 1
 end enum
 integer, parameter, public :: SUNNonlinSolAutoType = kind(SUNNONLINSOL_AUTO_FIXEDPOINT)
 public :: SUNNONLINSOL_AUTO_FIXEDPOINT, SUNNONLINSOL_AUTO_NEWTON

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct SUNNonlinearSolverContent_Auto_
 type, public :: SUNNonlinearSolverContent_Auto_
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_active_solver_type => swigf_SUNNonlinearSolverContent_Auto__active_solver_type_set
  procedure :: get_active_solver_type => swigf_SUNNonlinearSolverContent_Auto__active_solver_type_get
  procedure :: set_fp_solver => swigf_SUNNonlinearSolverContent_Auto__fp_solver_set
  procedure :: get_fp_solver => swigf_SUNNonlinearSolverContent_Auto__fp_solver_get
  procedure :: set_newton_solver => swigf_SUNNonlinearSolverContent_Auto__newton_solver_set
  procedure :: get_newton_solver => swigf_SUNNonlinearSolverContent_Auto__newton_solver_get
  procedure :: set_getconvrate_fn => swigf_SUNNonlinearSolverContent_Auto__getconvrate_fn_set
  procedure :: get_getconvrate_fn => swigf_SUNNonlinearSolverContent_Auto__getconvrate_fn_get
  procedure :: set_getconvrate_data => swigf_SUNNonlinearSolverContent_Auto__getconvrate_data_set
  procedure :: get_getconvrate_data => swigf_SUNNonlinearSolverContent_Auto__getconvrate_data_get
  procedure :: set_fp_to_newt_delay => swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_set
  procedure :: get_fp_to_newt_delay => swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_get
  procedure :: set_newt_to_fp_delay => swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_set
  procedure :: get_newt_to_fp_delay => swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_get
  procedure :: set_num_solves_since_switch => swigf_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R108T
  procedure :: get_num_solves_since_switch => swigf_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R0ZYQ
  procedure :: set_newt_to_fp_threshold => swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_set
  procedure :: get_newt_to_fp_threshold => swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_get
  procedure :: set_fp_to_newt_threshold => swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_set
  procedure :: get_fp_to_newt_threshold => swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_get
  procedure :: set_num_iters => swigf_SUNNonlinearSolverContent_Auto__num_iters_set
  procedure :: get_num_iters => swigf_SUNNonlinearSolverContent_Auto__num_iters_get
  procedure :: set_num_conv_fails => swigf_SUNNonlinearSolverContent_Auto__num_conv_fails_set
  procedure :: get_num_conv_fails => swigf_SUNNonlinearSolverContent_Auto__num_conv_fails_get
  procedure :: set_switch_count => swigf_SUNNonlinearSolverContent_Auto__switch_count_set
  procedure :: get_switch_count => swigf_SUNNonlinearSolverContent_Auto__switch_count_get
  procedure :: set_fp_num_iters_total => swigf_SUNNonlinearSolverContent_Auto__fp_num_iters_total_set
  procedure :: get_fp_num_iters_total => swigf_SUNNonlinearSolverContent_Auto__fp_num_iters_total_get
  procedure :: set_newton_num_iters_total => swigf_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENVP
  procedure :: get_newton_num_iters_total => swigf_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENLM
  procedure :: set_fp_num_conv_fails_total => swigf_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM8HS
  procedure :: get_fp_num_conv_fails_total => swigf_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM87P
  procedure :: set_newton_num_conv_fails_total => swigf_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99GJV
  procedure :: get_newton_num_conv_fails_total => swigf_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99G9S
  procedure :: set_auto_ctest_data => swigf_SUNNonlinearSolverContent_Auto__auto_ctest_data_set
  procedure :: get_auto_ctest_data => swigf_SUNNonlinearSolverContent_Auto__auto_ctest_data_get
  procedure :: release => swigf_release_SUNNonlinearSolverContent_Auto_
  procedure, private :: swigf_SUNNonlinearSolverContent_Auto__op_assign__
  generic :: assignment(=) => swigf_SUNNonlinearSolverContent_Auto__op_assign__
 end type SUNNonlinearSolverContent_Auto_
 interface SUNNonlinearSolverContent_Auto_
  module procedure swigf_create_SUNNonlinearSolverContent_Auto_
 end interface
 public :: FSUNNonlinSol_Auto
 public :: FSUNNonlinSolGetType_Auto
 public :: FSUNNonlinSolInitialize_Auto
 public :: FSUNNonlinSolSolve_Auto
 public :: FSUNNonlinSolFree_Auto
 public :: FSUNNonlinSolSetSysFns_Auto
 public :: FSUNNonlinSolSetConvTestFn_Auto
 public :: FSUNNonlinSolSetLSetupFn_Auto
 public :: FSUNNonlinSolSetLSolveFn_Auto
 type, public :: SWIGTYPE_p_p_char
  type(SwigClassWrapper), public :: swigdata
 end type
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 public :: FSUNNonlinSolSetOptions_Auto
 public :: FSUNNonlinSolSetNormFn_Auto
 public :: FSUNNonlinSolSetMaxIters_Auto
 public :: FSUNNonlinSolSetGetConvRateFn_Auto
 public :: FSUNNonlinSolSetGetUpdateNormFn_Auto
 public :: FSUNNonlinSolSetSwitchingParameters_Auto
 public :: FSUNNonlinSolGetFixedPointSolver_Auto
 public :: FSUNNonlinSolGetNewtonSolver_Auto
 public :: FSUNNonlinSolGetActiveSolverType_Auto
 public :: FSUNNonlinSolGetSwitchCount_Auto
 public :: FSUNNonlinSolGetNumIters_Auto
 public :: FSUNNonlinSolGetTotalNumItersByType_Auto
 public :: FSUNNonlinSolGetCurIter_Auto
 public :: FSUNNonlinSolGetNumConvFails_Auto
 public :: FSUNNonlinSolGetTotalNumConvFailsByType_Auto

! WRAPPER DECLARATIONS
interface
subroutine swigc_SUNNonlinearSolverContent_Auto__active_solver_type_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__active_solver_type_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__active_solver_type_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__active_solver_type_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__fp_solver_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_solver_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__fp_solver_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_solver_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__newton_solver_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newton_solver_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__newton_solver_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newton_solver_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__getconvrate_fn_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__getconvrate_fn_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__getconvrate_fn_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__getconvrate_fn_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__getconvrate_data_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__getconvrate_data_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__getconvrate_data_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__getconvrate_data_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R108T(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__num_solves_since_switch_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R0ZYQ(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__num_solves_since_switch_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__num_iters_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__num_iters_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__num_iters_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__num_iters_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__num_conv_fails_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__num_conv_fails_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__num_conv_fails_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__num_conv_fails_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__switch_count_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__switch_count_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__switch_count_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__switch_count_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__fp_num_iters_total_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_num_iters_total_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__fp_num_iters_total_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_num_iters_total_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENVP(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newton_num_iters_total_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENLM(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newton_num_iters_total_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM8HS(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_total_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM87P(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_total_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99GJV(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newton_num_conv_fails_total_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99G9S(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__newton_num_conv_fails_total_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_SUNNonlinearSolverContent_Auto__auto_ctest_data_set(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__auto_ctest_data_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNNonlinearSolverContent_Auto__auto_ctest_data_get(farg1) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__auto_ctest_data_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_SUNNonlinearSolverContent_Auto_() &
bind(C, name="_wrap_new_SUNNonlinearSolverContent_Auto_") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SUNNonlinearSolverContent_Auto_(farg1) &
bind(C, name="_wrap_delete_SUNNonlinearSolverContent_Auto_")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SUNNonlinearSolverContent_Auto__op_assign__(farg1, farg2) &
bind(C, name="_wrap_SUNNonlinearSolverContent_Auto__op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_FSUNNonlinSol_Auto(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNNonlinSol_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR) :: fresult
end function

function swigc_FSUNNonlinSolGetType_Auto(farg1) &
bind(C, name="_wrap_FSUNNonlinSolGetType_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolInitialize_Auto(farg1) &
bind(C, name="_wrap_FSUNNonlinSolInitialize_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSolve_Auto(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_FSUNNonlinSolSolve_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
real(C_DOUBLE), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
type(C_PTR), value :: farg7
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolFree_Auto(farg1) &
bind(C, name="_wrap_FSUNNonlinSolFree_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetSysFns_Auto(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSolSetSysFns_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_FUNPTR), value :: farg2
type(C_FUNPTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetConvTestFn_Auto(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSolSetConvTestFn_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_FUNPTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetLSetupFn_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolSetLSetupFn_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_FUNPTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetLSolveFn_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolSetLSolveFn_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_FUNPTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetOptions_Auto(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FSUNNonlinSolSetOptions_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(C_PTR), value :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: farg3
integer(C_INT), intent(in) :: farg4
type(SwigClassWrapper) :: farg5
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetNormFn_Auto(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSolSetNormFn_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_FUNPTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetMaxIters_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolSetMaxIters_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetGetConvRateFn_Auto(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSolSetGetConvRateFn_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_FUNPTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetGetUpdateNormFn_Auto(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSolSetGetUpdateNormFn_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_FUNPTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolSetSwitchingParameters_Auto(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FSUNNonlinSolSetSwitchingParameters_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
integer(C_LONG), intent(in) :: farg3
real(C_DOUBLE), intent(in) :: farg4
integer(C_LONG), intent(in) :: farg5
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetFixedPointSolver_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetFixedPointSolver_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetNewtonSolver_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetNewtonSolver_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetActiveSolverType_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetActiveSolverType_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetSwitchCount_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetSwitchCount_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetNumIters_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetNumIters_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetTotalNumItersByType_Auto(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSolGetTotalNumItersByType_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetCurIter_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetCurIter_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetNumConvFails_Auto(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetNumConvFails_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetTotalNumConvFailsByType_Auto(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSolGetTotalNumConvFailsByType_Auto") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine swigf_SUNNonlinearSolverContent_Auto__active_solver_type_set(self, active_solver_type)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(SUNNonlinSolAutoType), intent(in) :: active_solver_type
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = active_solver_type
call swigc_SUNNonlinearSolverContent_Auto__active_solver_type_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__active_solver_type_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SUNNonlinSolAutoType) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__active_solver_type_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__fp_solver_set(self, fp_solver)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(SUNNonlinearSolver), target, intent(inout) :: fp_solver
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = c_loc(fp_solver)
call swigc_SUNNonlinearSolverContent_Auto__fp_solver_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__fp_solver_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNNonlinearSolver), pointer :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__fp_solver_get(farg1)
call c_f_pointer(fresult, swig_result)
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__newton_solver_set(self, newton_solver)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(SUNNonlinearSolver), target, intent(inout) :: newton_solver
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = c_loc(newton_solver)
call swigc_SUNNonlinearSolverContent_Auto__newton_solver_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__newton_solver_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNNonlinearSolver), pointer :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__newton_solver_get(farg1)
call c_f_pointer(fresult, swig_result)
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__getconvrate_fn_set(self, getconvrate_fn)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_FUNPTR), intent(in), value :: getconvrate_fn
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 

farg1 = self%swigdata
farg2 = getconvrate_fn
call swigc_SUNNonlinearSolverContent_Auto__getconvrate_fn_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__getconvrate_fn_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_FUNPTR) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_FUNPTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__getconvrate_fn_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__getconvrate_data_set(self, getconvrate_data)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_PTR) :: getconvrate_data
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = getconvrate_data
call swigc_SUNNonlinearSolverContent_Auto__getconvrate_data_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__getconvrate_data_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__getconvrate_data_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_set(self, fp_to_newt_delay)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: fp_to_newt_delay
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = fp_to_newt_delay
call swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_set(self, newt_to_fp_delay)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: newt_to_fp_delay
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = newt_to_fp_delay
call swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R108T(self, num_solves_since_switch)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: num_solves_since_switch
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = num_solves_since_switch
call swigc_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R108T(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R0ZYQ(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__num_solves_since_sw1R0ZYQ(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_set(self, newt_to_fp_threshold)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
real(C_DOUBLE), intent(in) :: newt_to_fp_threshold
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = newt_to_fp_threshold
call swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_set(self, fp_to_newt_threshold)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
real(C_DOUBLE), intent(in) :: fp_to_newt_threshold
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = fp_to_newt_threshold
call swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__num_iters_set(self, num_iters)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: num_iters
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = num_iters
call swigc_SUNNonlinearSolverContent_Auto__num_iters_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__num_iters_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__num_iters_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__num_conv_fails_set(self, num_conv_fails)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: num_conv_fails
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = num_conv_fails
call swigc_SUNNonlinearSolverContent_Auto__num_conv_fails_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__num_conv_fails_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__num_conv_fails_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__switch_count_set(self, switch_count)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: switch_count
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = switch_count
call swigc_SUNNonlinearSolverContent_Auto__switch_count_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__switch_count_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__switch_count_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__fp_num_iters_total_set(self, fp_num_iters_total)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: fp_num_iters_total
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = fp_num_iters_total
call swigc_SUNNonlinearSolverContent_Auto__fp_num_iters_total_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__fp_num_iters_total_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__fp_num_iters_total_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENVP(self, newton_num_iters_total)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: newton_num_iters_total
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = newton_num_iters_total
call swigc_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENVP(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENLM(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__newton_num_iters_to1WENLM(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM8HS(self, fp_num_conv_fails_total)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: fp_num_conv_fails_total
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = fp_num_conv_fails_total
call swigc_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM8HS(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM87P(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_t1FM87P(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99GJV(self, newton_num_conv_fails_total)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG), intent(in) :: newton_num_conv_fails_total
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = newton_num_conv_fails_total
call swigc_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99GJV(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99G9S(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__newton_num_conv_fail99G9S(farg1)
swig_result = fresult
end function

subroutine swigf_SUNNonlinearSolverContent_Auto__auto_ctest_data_set(self, auto_ctest_data)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_PTR) :: auto_ctest_data
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = auto_ctest_data
call swigc_SUNNonlinearSolverContent_Auto__auto_ctest_data_set(farg1, farg2)
end subroutine

function swigf_SUNNonlinearSolverContent_Auto__auto_ctest_data_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(SUNNonlinearSolverContent_Auto_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNNonlinearSolverContent_Auto__auto_ctest_data_get(farg1)
swig_result = fresult
end function

function swigf_create_SUNNonlinearSolverContent_Auto_() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SUNNonlinearSolverContent_Auto_) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SUNNonlinearSolverContent_Auto_()
self%swigdata = fresult
end function

subroutine swigf_release_SUNNonlinearSolverContent_Auto_(self)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SUNNonlinearSolverContent_Auto_(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SUNNonlinearSolverContent_Auto__op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SUNNonlinearSolverContent_Auto_), intent(inout) :: self
type(SUNNonlinearSolverContent_Auto_), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SUNNonlinearSolverContent_Auto__op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function FSUNNonlinSol_Auto(y, m, initial_solver_type, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNNonlinearSolver), pointer :: swig_result
type(N_Vector), target, intent(inout) :: y
integer(C_INT), intent(in) :: m
integer(SUNNonlinSolAutoType), intent(in) :: initial_solver_type
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 
integer(C_INT) :: farg3 
type(C_PTR) :: farg4 

farg1 = c_loc(y)
farg2 = m
farg3 = initial_solver_type
farg4 = sunctx
fresult = swigc_FSUNNonlinSol_Auto(farg1, farg2, farg3, farg4)
call c_f_pointer(fresult, swig_result)
end function

function FSUNNonlinSolGetType_Auto(nls) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SUNNonlinearSolver_Type) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(nls)
fresult = swigc_FSUNNonlinSolGetType_Auto(farg1)
swig_result = fresult
end function

function FSUNNonlinSolInitialize_Auto(nls) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(nls)
fresult = swigc_FSUNNonlinSolInitialize_Auto(farg1)
swig_result = fresult
end function

function FSUNNonlinSolSolve_Auto(nls, y0, ycor, w, tol, callsetup, mem) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(N_Vector), target, intent(inout) :: y0
type(N_Vector), target, intent(inout) :: ycor
type(N_Vector), target, intent(inout) :: w
real(C_DOUBLE), intent(in) :: tol
integer(C_INT), intent(in) :: callsetup
type(C_PTR) :: mem
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
real(C_DOUBLE) :: farg5 
integer(C_INT) :: farg6 
type(C_PTR) :: farg7 

farg1 = c_loc(nls)
farg2 = c_loc(y0)
farg3 = c_loc(ycor)
farg4 = c_loc(w)
farg5 = tol
farg6 = callsetup
farg7 = mem
fresult = swigc_FSUNNonlinSolSolve_Auto(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
swig_result = fresult
end function

function FSUNNonlinSolFree_Auto(nls) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(nls)
fresult = swigc_FSUNNonlinSolFree_Auto(farg1)
swig_result = fresult
end function

function FSUNNonlinSolSetSysFns_Auto(nls, root_fn, fixed_point_fn) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), intent(in), value :: root_fn
type(C_FUNPTR), intent(in), value :: fixed_point_fn
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_FUNPTR) :: farg2 
type(C_FUNPTR) :: farg3 

farg1 = c_loc(nls)
farg2 = root_fn
farg3 = fixed_point_fn
fresult = swigc_FSUNNonlinSolSetSysFns_Auto(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNNonlinSolSetConvTestFn_Auto(nls, ctestfn, ctest_data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), intent(in), value :: ctestfn
type(C_PTR) :: ctest_data
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_FUNPTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(nls)
farg2 = ctestfn
farg3 = ctest_data
fresult = swigc_FSUNNonlinSolSetConvTestFn_Auto(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNNonlinSolSetLSetupFn_Auto(nls, lsetupfn) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), intent(in), value :: lsetupfn
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_FUNPTR) :: farg2 

farg1 = c_loc(nls)
farg2 = lsetupfn
fresult = swigc_FSUNNonlinSolSetLSetupFn_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolSetLSolveFn_Auto(nls, lsolvefn) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), intent(in), value :: lsolvefn
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_FUNPTR) :: farg2 

farg1 = c_loc(nls)
farg2 = lsolvefn
fresult = swigc_FSUNNonlinSolSetLSolveFn_Auto(farg1, farg2)
swig_result = fresult
end function


subroutine SWIG_string_to_chararray(string, chars, wrap)
  use, intrinsic :: ISO_C_BINDING
  character(kind=C_CHAR, len=*), intent(IN) :: string
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(OUT) :: chars
  type(SwigArrayWrapper), intent(OUT) :: wrap
  integer :: i

  allocate(character(kind=C_CHAR) :: chars(len(string) + 1))
  do i=1,len(string)
    chars(i) = string(i:i)
  end do
  i = len(string) + 1
  chars(i) = C_NULL_CHAR ! C string compatibility
  wrap%data = c_loc(chars)
  wrap%size = len(string)
end subroutine

function FSUNNonlinSolSetOptions_Auto(nls, nlsid, file_name, argc, argv) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
character(kind=C_CHAR, len=*), target :: nlsid
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
character(kind=C_CHAR, len=*), target :: file_name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_chars
integer(C_INT), intent(in) :: argc
class(SWIGTYPE_p_p_char), intent(in) :: argv
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(SwigArrayWrapper) :: farg2 
type(SwigArrayWrapper) :: farg3 
integer(C_INT) :: farg4 
type(SwigClassWrapper) :: farg5 

farg1 = c_loc(nls)
call SWIG_string_to_chararray(nlsid, farg2_chars, farg2)
call SWIG_string_to_chararray(file_name, farg3_chars, farg3)
farg4 = argc
farg5 = argv%swigdata
fresult = swigc_FSUNNonlinSolSetOptions_Auto(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function FSUNNonlinSolSetNormFn_Auto(nls, normfn, norm_fn_data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), intent(in), value :: normfn
type(C_PTR) :: norm_fn_data
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_FUNPTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(nls)
farg2 = normfn
farg3 = norm_fn_data
fresult = swigc_FSUNNonlinSolSetNormFn_Auto(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNNonlinSolSetMaxIters_Auto(nls, maxiters) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_INT), intent(in) :: maxiters
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(nls)
farg2 = maxiters
fresult = swigc_FSUNNonlinSolSetMaxIters_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolSetGetConvRateFn_Auto(nls, getconvratefn, getconvrate_data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), intent(in), value :: getconvratefn
type(C_PTR) :: getconvrate_data
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_FUNPTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(nls)
farg2 = getconvratefn
farg3 = getconvrate_data
fresult = swigc_FSUNNonlinSolSetGetConvRateFn_Auto(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNNonlinSolSetGetUpdateNormFn_Auto(nls, getupdatenormfn, getupdatenorm_data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), intent(in), value :: getupdatenormfn
type(C_PTR) :: getupdatenorm_data
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_FUNPTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(nls)
farg2 = getupdatenormfn
farg3 = getupdatenorm_data
fresult = swigc_FSUNNonlinSolSetGetUpdateNormFn_Auto(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNNonlinSolSetSwitchingParameters_Auto(nls, newt_to_fp_threshold, newt_to_fp_delay, fp_to_newt_threshold, &
  fp_to_newt_delay) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
real(C_DOUBLE), intent(in) :: newt_to_fp_threshold
integer(C_LONG), intent(in) :: newt_to_fp_delay
real(C_DOUBLE), intent(in) :: fp_to_newt_threshold
integer(C_LONG), intent(in) :: fp_to_newt_delay
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 
integer(C_LONG) :: farg3 
real(C_DOUBLE) :: farg4 
integer(C_LONG) :: farg5 

farg1 = c_loc(nls)
farg2 = newt_to_fp_threshold
farg3 = newt_to_fp_delay
farg4 = fp_to_newt_threshold
farg5 = fp_to_newt_delay
fresult = swigc_FSUNNonlinSolSetSwitchingParameters_Auto(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function FSUNNonlinSolGetFixedPointSolver_Auto(nls, fp_nls) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_PTR), target, intent(inout) :: fp_nls
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(fp_nls)
fresult = swigc_FSUNNonlinSolGetFixedPointSolver_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetNewtonSolver_Auto(nls, newton_nls) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_PTR), target, intent(inout) :: newton_nls
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(newton_nls)
fresult = swigc_FSUNNonlinSolGetNewtonSolver_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetActiveSolverType_Auto(nls, active_solver_type) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(SUNNonlinSolAutoType), target, intent(inout) :: active_solver_type
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(active_solver_type)
fresult = swigc_FSUNNonlinSolGetActiveSolverType_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetSwitchCount_Auto(nls, switch_count) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_LONG), dimension(*), target, intent(inout) :: switch_count
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(switch_count(1))
fresult = swigc_FSUNNonlinSolGetSwitchCount_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetNumIters_Auto(nls, niters) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_LONG), dimension(*), target, intent(inout) :: niters
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(niters(1))
fresult = swigc_FSUNNonlinSolGetNumIters_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetTotalNumItersByType_Auto(nls, fp_iters, newt_iters) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_LONG), dimension(*), target, intent(inout) :: fp_iters
integer(C_LONG), dimension(*), target, intent(inout) :: newt_iters
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(nls)
farg2 = c_loc(fp_iters(1))
farg3 = c_loc(newt_iters(1))
fresult = swigc_FSUNNonlinSolGetTotalNumItersByType_Auto(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNNonlinSolGetCurIter_Auto(nls, iter) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_INT), dimension(*), target, intent(inout) :: iter
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(iter(1))
fresult = swigc_FSUNNonlinSolGetCurIter_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetNumConvFails_Auto(nls, nconvfails) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_LONG), dimension(*), target, intent(inout) :: nconvfails
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(nconvfails(1))
fresult = swigc_FSUNNonlinSolGetNumConvFails_Auto(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetTotalNumConvFailsByType_Auto(nls, fp_nconvfails, newt_nconvfails) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_LONG), dimension(*), target, intent(inout) :: fp_nconvfails
integer(C_LONG), dimension(*), target, intent(inout) :: newt_nconvfails
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(nls)
farg2 = c_loc(fp_nconvfails(1))
farg3 = c_loc(newt_nconvfails(1))
fresult = swigc_FSUNNonlinSolGetTotalNumConvFailsByType_Auto(farg1, farg2, farg3)
swig_result = fresult
end function


end module
