#! /bin/sh

rm -fr src/*.o src/*.so autom4te.cache config.log config.status inst/lib/*.a
rm -fr src/sundials
rm -fr src/Makevars
rm -fr inst/lib/cmake
rm -f configure~
# CRAN fix: remove generated src/Makevars so it is not included in the tarball
rm -f src/Makevars
rm -f config.log
rm -f config.status
#rm -f src/sundials-*.tar.gz
