# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS SUNDIALS::core_static SUNDIALS::nvecserial_static SUNDIALS::nvecmanyvector_static SUNDIALS::sunmatrixband_static SUNDIALS::sunmatrixdense_static SUNDIALS::sunmatrixsparse_static SUNDIALS::sunlinsolband_static SUNDIALS::sunlinsoldense_static SUNDIALS::sunlinsolpcg_static SUNDIALS::sunlinsolspbcgs_static SUNDIALS::sunlinsolspfgmr_static SUNDIALS::sunlinsolspgmr_static SUNDIALS::sunlinsolsptfqmr_static SUNDIALS::sunnonlinsolnewton_static SUNDIALS::sunnonlinsolfixedpoint_static SUNDIALS::arkode_static SUNDIALS::cvode_static SUNDIALS::cvodes_static SUNDIALS::ida_static SUNDIALS::idas_static SUNDIALS::kinsol_static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target SUNDIALS::core_static
add_library(SUNDIALS::core_static STATIC IMPORTED)

set_target_properties(SUNDIALS::core_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>"
)

# Create imported target SUNDIALS::nvecserial_static
add_library(SUNDIALS::nvecserial_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::nvecmanyvector_static
add_library(SUNDIALS::nvecmanyvector_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunmatrixband_static
add_library(SUNDIALS::sunmatrixband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunmatrixdense_static
add_library(SUNDIALS::sunmatrixdense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunmatrixsparse_static
add_library(SUNDIALS::sunmatrixsparse_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunlinsolband_static
add_library(SUNDIALS::sunlinsolband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static;SUNDIALS::sunmatrixband_static"
)

# Create imported target SUNDIALS::sunlinsoldense_static
add_library(SUNDIALS::sunlinsoldense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static;SUNDIALS::sunmatrixdense_static"
)

# Create imported target SUNDIALS::sunlinsolpcg_static
add_library(SUNDIALS::sunlinsolpcg_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunlinsolspbcgs_static
add_library(SUNDIALS::sunlinsolspbcgs_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunlinsolspfgmr_static
add_library(SUNDIALS::sunlinsolspfgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunlinsolspgmr_static
add_library(SUNDIALS::sunlinsolspgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunlinsolsptfqmr_static
add_library(SUNDIALS::sunlinsolsptfqmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunnonlinsolnewton_static
add_library(SUNDIALS::sunnonlinsolnewton_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::sunnonlinsolfixedpoint_static
add_library(SUNDIALS::sunnonlinsolfixedpoint_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::arkode_static
add_library(SUNDIALS::arkode_static STATIC IMPORTED)

set_target_properties(SUNDIALS::arkode_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::cvode_static
add_library(SUNDIALS::cvode_static STATIC IMPORTED)

set_target_properties(SUNDIALS::cvode_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::cvodes_static
add_library(SUNDIALS::cvodes_static STATIC IMPORTED)

set_target_properties(SUNDIALS::cvodes_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::ida_static
add_library(SUNDIALS::ida_static STATIC IMPORTED)

set_target_properties(SUNDIALS::ida_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::idas_static
add_library(SUNDIALS::idas_static STATIC IMPORTED)

set_target_properties(SUNDIALS::idas_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Create imported target SUNDIALS::kinsol_static
add_library(SUNDIALS::kinsol_static STATIC IMPORTED)

set_target_properties(SUNDIALS::kinsol_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/include;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-src/src/sundials;/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_static"
)

# Import target "SUNDIALS::core_static" for configuration "Release"
set_property(TARGET SUNDIALS::core_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::core_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sundials/libsundials_core.a"
  )

# Import target "SUNDIALS::nvecserial_static" for configuration "Release"
set_property(TARGET SUNDIALS::nvecserial_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/nvector/serial/libsundials_nvecserial.a"
  )

# Import target "SUNDIALS::nvecmanyvector_static" for configuration "Release"
set_property(TARGET SUNDIALS::nvecmanyvector_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/nvector/manyvector/libsundials_nvecmanyvector.a"
  )

# Import target "SUNDIALS::sunmatrixband_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunmatrix/band/libsundials_sunmatrixband.a"
  )

# Import target "SUNDIALS::sunmatrixdense_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunmatrix/dense/libsundials_sunmatrixdense.a"
  )

# Import target "SUNDIALS::sunmatrixsparse_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunmatrixsparse_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunmatrix/sparse/libsundials_sunmatrixsparse.a"
  )

# Import target "SUNDIALS::sunlinsolband_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunlinsol/band/libsundials_sunlinsolband.a"
  )

# Import target "SUNDIALS::sunlinsoldense_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsoldense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunlinsol/dense/libsundials_sunlinsoldense.a"
  )

# Import target "SUNDIALS::sunlinsolpcg_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolpcg_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunlinsol/pcg/libsundials_sunlinsolpcg.a"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunlinsol/spbcgs/libsundials_sunlinsolspbcgs.a"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunlinsol/spfgmr/libsundials_sunlinsolspfgmr.a"
  )

# Import target "SUNDIALS::sunlinsolspgmr_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolspgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunlinsol/spgmr/libsundials_sunlinsolspgmr.a"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunlinsol/sptfqmr/libsundials_sunlinsolsptfqmr.a"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunnonlinsol/newton/libsundials_sunnonlinsolnewton.a"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_static" for configuration "Release"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/sunnonlinsol/fixedpoint/libsundials_sunnonlinsolfixedpoint.a"
  )

# Import target "SUNDIALS::arkode_static" for configuration "Release"
set_property(TARGET SUNDIALS::arkode_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::arkode_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/arkode/libsundials_arkode.a"
  )

# Import target "SUNDIALS::cvode_static" for configuration "Release"
set_property(TARGET SUNDIALS::cvode_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::cvode_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/cvode/libsundials_cvode.a"
  )

# Import target "SUNDIALS::cvodes_static" for configuration "Release"
set_property(TARGET SUNDIALS::cvodes_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::cvodes_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/cvodes/libsundials_cvodes.a"
  )

# Import target "SUNDIALS::ida_static" for configuration "Release"
set_property(TARGET SUNDIALS::ida_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::ida_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/ida/libsundials_ida.a"
  )

# Import target "SUNDIALS::idas_static" for configuration "Release"
set_property(TARGET SUNDIALS::idas_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::idas_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/idas/libsundials_idas.a"
  )

# Import target "SUNDIALS::kinsol_static" for configuration "Release"
set_property(TARGET SUNDIALS::kinsol_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SUNDIALS::kinsol_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/quantilogy/Documents/GitHub/sn248/sundialr/src/sundials-build/src/kinsol/libsundials_kinsol.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
