---
title: "sundialr - An Interface to 'SUNDIALS' Ordinary Differential Equation (ODE) Solvers"
author: "Satyaprakash Nayak"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sundialr - A wrapper around CVODE, CVODES solvers from SUNDIALS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction
Ordinary Differential Equations (ODEs) describe the rate of change of dependent variables with respect to a single independent variable and are used in many fields to model behavior of the system. There are many good `C` libraries available to solve (i.e., integrate systems of ODEs) and [SUNDIALS](https://computation.llnl.gov/projects/sundials/sundials-software) available from the Lawrence Livermore National Laboratory is a one of the most popular and well-respected `C` library for solving non-stiff and stiff systems of ODEs.

Currently, this package provides an interface to the `CVODE` and `CVODES` function (serial version) in the library which is used to solve ODEs (or Initial Value Problems) and calculate sensitivities.

The two exported functions from the package are:

+ `CVODE` - 
+ `CVODES` - 

In future, we plan to provide interface for the other solvers (i.e., `IDA/IDAS` and `ARCODE` in the library also. Right now, this package serves as a test case for providing an interface to the `SUNDIALS` library for `R` users.

_One of the advantage of using this package is that all the source code of the `SUNDIALS` library is bundled with the package itself, so it does not require the `SUNDIALS` library to be installed on the machine separately (which is sometimes not trivial for Windows)._

## System of ODEs 
As described in the link above,  the problem is from chemical kinetics, and consists of the following three rate equations:         

$$ 
\begin{aligned}
\frac{dy_1}{dt} &= -.04 \times y_1 + 10^4 \times y_2 \times y_3  \\ 
\frac{dy_2}{dt} &= .04 \times y_1 - 10^4 \times y_2 \times y_3 - 3 \times 10^7  \times y_2^2 \\
\frac{dy_3}{dt} &= 3 \times 10^7 \times y_2^2 
\end{aligned}
$$


on the interval from time 

$$ t = 0.0$$ 
to 
$$ t = 4 \times 10^{10} $$ 
with initial conditions: 
$$ y_1  = 1.0 , ~y_2 = y_3 = 0 $$ 

**The problem is stiff.**

The original example , While integrating the system, also uses the rootfinding feature to find the points at which 

$$ y_1 = 1 \times 10^{-4} $$
or at which 
$$ y_3 = 0.01 $$
but currently root-finding is not supported in this version. As, in the original example this package also solves the problem with the BDF method, Newton iteration with the SUNDENSE dense linear solver, however, without a user-supplied Jacobian routine (unlike the original example). It uses a scalar relative tolerance and a vector absolute
tolerance (which can be provided as an input). Output is printed in decades from 
$$ t = 0.4 $$ 
to 
$$ t = 4 \times 10^{10} $$


## Writing the Differential Equations

### Using R
Differential equations can be written as an `R` function or as an `Rcpp` function. Differential equations function must be written as
```r
function(t, y, p){
  # code to write differential equations
  # using prameter vector (p) and state/entity vector (y)
  # should return `ydot`, the vector representing
  # rate of change of entities in `y`
}
```
where `t` represents time, `y` is the vector describing the values of states/entities of the ODE system at time `t` and `p` is the vector of parameters used to define the ODEs. The output of this function is a vector of rate of change of entities of `y`.

The key aspect to keep in mind is that the signature of the function must be `function(t,y,p)`. As an example, we try to solve the `cv_Roberts_dns.c` problem described above, the original code can be found [here](https://github.com/LLNL/sundials/blob/master/examples/cvode/serial/cvRoberts_dns.c). An example of an `R` function is as follows:

```r
ODE_R <- function(t, y, p){

   ## initialize the derivative vector
   ydot <- vector(mode = "numeric", length = length(y))
   
   ## p (parameter vector) is  [-0.04 1e04 3e07]
   
   ydot[1] = p[1]*y[1] + p[2]*y[2]*y[3]
   ydot[2] = -p[1]*y[1] - p[2]*y[2]*y[3] - p[3]*y[2]*y[2]
   ydot[3] = p[3]*y[2]*y[2]

   ydot      ## return ydot
}
```
where `p` is a parameter vector with the values `[-0.04 1e04 3e07]`.

### Using Rcpp

Also, since this package using `Rcpp` to bundle the C code, we can use the notation used in `Rcpp` to describe the system of ODEs. The `cv_Roberts_dns` problem describe above can be described in an `Rcpp` function as follows (indices in `C++` start from `0`, functions need to declare their return type, here `NumericVector`  and every expression ends in a semicolon, `;`) :

```c++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector ODE_Rcpp (double t, NumericVector y){

  // Initialize ydot filled with zeros
  NumericVector ydot(y.length());

  // p (parameter vector) is [-0.04 1e04 3e07]
  ydot[0] = p[0] * y[0] + p[1] * y[1] * y[2];
  ydot[1] = -p[0]*y[0] - p[1]*y[1]*y[2] - p[2]*y[1]*y[1]
  ydot[2] = p[2] * y[1] * y[1];

  return ydot;

}
```
The above is a re-write of the `cvRoberts_dns` example in the documentation of `CVODE`. The original example can be found the document [here](https://computation.llnl.gov/sites/default/files/public/cv_examples.pdf).

## Putting everything together
The entire `R` file to create right hand side of ODE function (which calculates rates of change) is as follows (also found in `/inst/examples/cv_Roberts_dns.r`):

```r
# ODEs described by an R function
ODE_R <- function(t, y, p){

   ## initialize the derivative vector
   ydot <- vector(mode = "numeric", length = length(y))
   
   ## p (parameter vector) is  [-0.04 1e04 3e07]
   
   ydot[1] = p[1]*y[1] + p[2]*y[2]*y[3]
   ydot[2] = -p[1]*y[1] - p[2]*y[2]*y[3] - p[3]*y[2]*y[2]
   ydot[3] = p[3]*y[2]*y[2]

   ydot      ## return ydot
}

# ODEs can also be described using Rcpp
Rcpp::sourceCpp(code = '

#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector ODE_Rcpp (double t, NumericVector y){

  // Initialize ydot filled with zeros
  NumericVector ydot(y.length());

  // p (parameter vector) is [-0.04 1e04 3e07]
  ydot[0] = p[0] * y[0] + p[1] * y[1] * y[2];
  ydot[1] = -p[0]*y[0] - p[1]*y[1]*y[2] - p[2]*y[1]*y[1]
  ydot[2] = p[2] * y[1] * y[1];

  return ydot;

}')

# Generate time vector, IC and call cvode to solve the equations
# R code to genrate time vector, IC and solve the equations
time_vec <- c(0.0, 0.4, 4.0, 40.0, 4E2, 4E3, 4E4, 4E5, 4E6, 4E7, 4E8, 4E9, 4E10)
IC <- c(1,0,0)
params <- c(0.04, 10000, 30000000)
reltol <- 1e-04
abstol <- c(1e-8,1e-14,1e-6)

## Solving the ODEs using cvode function
df1 <- cvode(time_vec, IC, ODE_R , params, reltol, abstol)           ## using R
df2 <- cvode(time_vec, IC, ODE_Rcpp , params, reltol, abstol)        ## using Rcpp

## Check that both solutions are identical
# identical(df1, df2)
```

The final output is the `df1` matrix in which first column is time, second, third
and fourth column are the values of `y1`, `y2` and `y3` respectively.

```r
> df1
       [,1]         [,2]         [,3]       [,4]
 [1,] 0e+00 1.000000e+00 0.000000e+00 0.00000000
 [2,] 4e-01 9.851641e-01 3.386242e-05 0.01480205
 [3,] 4e+00 9.055097e-01 2.240338e-05 0.09446793
 [4,] 4e+01 7.158016e-01 9.185043e-06 0.28418924
 [5,] 4e+02 4.505209e-01 3.222826e-06 0.54947590
 [6,] 4e+03 1.832217e-01 8.943516e-07 0.81677741
 [7,] 4e+04 3.898091e-02 1.621669e-07 0.96101893
 [8,] 4e+05 4.936971e-03 1.984450e-08 0.99506301
 [9,] 4e+06 5.170103e-04 2.069098e-09 0.99948299
[10,] 4e+07 5.204927e-05 2.082078e-10 0.99994795
[11,] 4e+08 5.184946e-06 2.073989e-11 0.99999482
[12,] 4e+09 5.246212e-07 2.098486e-12 0.99999948
[13,] 4e+10 6.043000e-08 2.417200e-13 0.99999994
```

## System of ODEs for Parameter Sensitivities
Sensitivity with respect to the parameters of the ODE system can be calculated
using `CVODES` function. This package implements Forward Sensitivity Analysis
from `CVODES` function (see the example `cvRoberts_FSA_dns.c` from the link [here](https://github.com/LLNL/sundials/blob/master/examples/cvodes/serial/cvsRoberts_FSA_dns.c)). Briefly, given the ODE system as described below

$$ 
\begin{aligned}
\frac{dy_1}{dt} &= -p_1y_1 + p_2y_2y_3  \\ 
\frac{dy_2}{dt} &= p_1y_1 - p_2y_2y_3 - p_3y_2^2 \\
\frac{dy_3}{dt} &= p_3y_2^2 
\end{aligned}
$$
with the same initial conditions as above (i.e., $y_1 = 0, y_2 = y_3 = 0$) and 
$p_1 = 0.04, \quad p_2 = 10^4, \quad p_3 = 3\times10^7$. The Sensitivity equation
(taken from `cvs_guide.pdf`) that is solved can be given by
$$
\begin{aligned}
\frac{ds}{dt} = 
\left[\begin{array}
{ccc}
-p_1 & p_2y_3 & p_2y_2 \\
p_1 & -p_2y_3-2p_3y_2 & -p_2y_2 \\
0 & 2p_3y_2 & 0
\end{array}\right]s_i + \frac{\partial f}{\partial p_i}, 
\quad s_i(t_0) = 
\left[\begin{array}  {c} 0 \\ 0 \\ 0 \end{array}\right], \quad i = 1, 2, 3 
\end{aligned}
$$
where
$$
\frac{\partial f}{\partial p_1} = \left[\begin{array}  {c} -y_1 \\ y_1 \\ 0 \end{array}\right],
\quad \frac{\partial f}{\partial p_2} = \left[\begin{array}  {c} y_2y_3 \\ -y_2y_3 \\ 0 \end{array}\right],
\quad
\frac{\partial f}{\partial p_3} = \left[\begin{array}  {c} 0 \\ -y_2^2 \\ y_2^2 \end{array}\right]
$$
In the original `CVODES` interface from `SUNDIALS`, the sensitivity equations
can either be provided by the user or can be calculated using numerical interpolation
by the solver. Here, I have only included the numerical interpolation version and
currently the user cannot specify the sensitivity equations. However, in the future
versions I will provide an ability to specify user-defined Jacobian as well as 
user-defined sensitivity equations. 

Also, currently, sensitivities are calculated with respect to all parameters of the
system. I plan to provide in future, an ability to specify specific particular 
parameters for which sensitivity is desired. Currently, `SIMULATEOUS` and `STAGGERED`
methods of sensitivity calculations from the `SUNDIALS` library are supported in this
package.

## Calculation of Sensitivities using `CVODES`
Once, the system of ODEs has been defined using the instructions provided above, 
sensitivities can be easily calculated using the `cvodes` function using the 
function call below:

```r
df1 <- cvodes(time_vec, IC, ODE_R , params, reltol, abstol,"STG",F)  ## using R
df2 <- cvodes(time_vec, IC, ODE_Rcpp , params, reltol, abstol,"STG",F)  ## using R
```
The additional arguments in `cvodes` specify the senstivity calculation method
to be used (`STG` for `STAGGERED` or `SIM` for `SIMULATENOUS`) and flag for error control
(either `T` or `F`).

The output of `cvodes` is a matrix with number of rows equal to the length of
`time_vec` and the number of columns being equal to length of (`y` + `p`). The 
first columns is for time, the next `length(y)` columns are for the solution of 
the ODE system (i.e, same as the output of `cvode`) and the final `length(p)`
columns are for sensitivity values. For example the output of calling `cvodes`
above gives the following matrix:
```r
> df1
       [,1]         [,2]         [,3]       [,4]          [,5]          [,6]         [,7]
 [1,] 0e+00 1.000000e+00 0.000000e+00 0.00000000  0.000000e+00  0.000000e+00 0.000000e+00
 [2,] 4e-01 9.851693e-01 3.386341e-05 0.01479681 -1.573297e-11 -5.289692e-13 1.626194e-11
 [3,] 4e+00 9.055161e-01 2.240400e-05 0.09446146 -4.932970e-10 -2.762408e-13 4.935732e-10
 [4,] 4e+01 7.158367e-01 9.185415e-06 0.28415410 -2.288274e-09 -1.138015e-13 2.288387e-09
 [5,] 4e+02 4.505277e-01 3.222987e-06 0.54946907 -3.789554e-09 -4.994795e-14 3.789604e-09
 [6,] 4e+03 1.832276e-01 8.943693e-07 0.81677155 -3.134824e-09 -1.875976e-14 3.134843e-09
 [7,] 4e+04 3.898309e-02 1.621755e-07 0.96101675 -1.047876e-09 -4.536508e-15 1.047881e-09
 [8,] 4e+05 4.937661e-03 1.984756e-08 0.99506232 -1.574929e-10 -6.362045e-16 1.574935e-10
 [9,] 4e+06 5.167720e-04 2.068142e-09 0.99948323 -1.711080e-11 -6.851356e-17 1.711087e-11
[10,] 4e+07 5.201894e-05 2.080864e-10 0.99994798 -1.732552e-12 -6.930923e-18 1.732559e-12
[11,] 4e+08 5.208807e-06 2.083534e-11 0.99999479 -1.737821e-13 -6.951356e-19 1.737828e-13
[12,] 4e+09 4.975680e-07 1.990273e-12 0.99999950 -1.804535e-14 -7.218146e-20 1.804542e-14
[13,] 4e+10 3.837583e-08 1.535033e-13 0.99999996 -1.727574e-15 -6.910296e-21 1.727581e-15
```
In the output `df1` above, the first column is for time, the next three (length of `y` is 3) columns are the solution of the ODE system (i.e., the first column in the value of $y_1$ at different times and so on). Thus, the first four columns are exactly same as the output of `CVODE` function. The values from column 4 onwards are the sensitivity values, i.e. the values in the fifth column are the values for sensitivity with respect to the first parameter $p_1$ and so on.


## Summary
The package `sundialr` provides a way to interface with the famous 'SUNDIALS' C library 
to solver initial value problems. The package allows differential equation to be written 
in `R` or using `Rcpp`. Currently only a single initialization is supported, but we plan to add repeated initializations (e.g., repeated dosing) in near future. In addition, other solvers from the C library such as`IDA/IDAS` and `ARKODE` will be added soon.
