/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * Programmer(s): Auto-generated by swig.
 * ---------------------------------------------------------------
 * SUNDIALS Copyright Start
 * Copyright (c) 2025-2026, Lawrence Livermore National Security,
 * University of Maryland Baltimore County, and the SUNDIALS contributors.
 * Copyright (c) 2013-2025, Lawrence Livermore National Security
 * and Southern Methodist University.
 * Copyright (c) 2002-2013, Lawrence Livermore National Security.
 * All rights reserved.
 *
 * See the top-level LICENSE and NOTICE files for details.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * SUNDIALS Copyright End
 * -------------------------------------------------------------*/

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* qualifier for exported *const* global data variables*/
#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13




#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
    SWIG_MEM_CONST = 0x04
};


#define SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    if ((SWIG_CLASS_WRAPPER).cmemflags & SWIG_MEM_CONST) { \
        SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
            "Cannot pass const " TYPENAME " (class " FNAME ") " \
            "as a mutable reference", \
            RETURNNULL); \
    }


#define SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(SWIG_CLASS_WRAPPER).cptr) { \
    SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


#define SWIG_check_mutable_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL); \
    SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL);


#include <stdio.h>
#if defined(_MSC_VER) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040000 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include "sundials/sundials_nonlinearsolver.h"


#include "sunnonlinsol/sunnonlinsol_auto.h"


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}


typedef struct {
    void* data;
    size_t size;
} SwigArrayWrapper;


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}

SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__active_solver_type_set(SwigClassWrapper const *farg1, int const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinSolAutoType arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::active_solver_type", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (SUNNonlinSolAutoType)(*farg2);
  if (arg1) (arg1)->active_solver_type = arg2;
}


SWIGEXPORT int _wrap_SUNNonlinearSolverContent_Auto__active_solver_type_get(SwigClassWrapper const *farg1) {
  int fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinSolAutoType result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::active_solver_type", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (SUNNonlinSolAutoType) ((arg1)->active_solver_type);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__fp_solver_set(SwigClassWrapper const *farg1, SUNNonlinearSolver farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinearSolver arg2 = (SUNNonlinearSolver) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_solver", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (SUNNonlinearSolver)(farg2);
  if (arg1) (arg1)->fp_solver = arg2;
}


SWIGEXPORT SUNNonlinearSolver _wrap_SUNNonlinearSolverContent_Auto__fp_solver_get(SwigClassWrapper const *farg1) {
  SUNNonlinearSolver fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinearSolver result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_solver", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (SUNNonlinearSolver) ((arg1)->fp_solver);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__newton_solver_set(SwigClassWrapper const *farg1, SUNNonlinearSolver farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinearSolver arg2 = (SUNNonlinearSolver) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newton_solver", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (SUNNonlinearSolver)(farg2);
  if (arg1) (arg1)->newton_solver = arg2;
}


SWIGEXPORT SUNNonlinearSolver _wrap_SUNNonlinearSolverContent_Auto__newton_solver_get(SwigClassWrapper const *farg1) {
  SUNNonlinearSolver fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinearSolver result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newton_solver", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (SUNNonlinearSolver) ((arg1)->newton_solver);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__getconvrate_fn_set(SwigClassWrapper const *farg1, SUNNonlinSolGetConvRateFn farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinSolGetConvRateFn arg2 = (SUNNonlinSolGetConvRateFn) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::getconvrate_fn", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (SUNNonlinSolGetConvRateFn)(farg2);
  if (arg1) (arg1)->getconvrate_fn = arg2;
}


SWIGEXPORT SUNNonlinSolGetConvRateFn _wrap_SUNNonlinearSolverContent_Auto__getconvrate_fn_get(SwigClassWrapper const *farg1) {
  SUNNonlinSolGetConvRateFn fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  SUNNonlinSolGetConvRateFn result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::getconvrate_fn", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (SUNNonlinSolGetConvRateFn) ((arg1)->getconvrate_fn);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__getconvrate_data_set(SwigClassWrapper const *farg1, void *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  void *arg2 = (void *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::getconvrate_data", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (void *)(farg2);
  if (arg1) (arg1)->getconvrate_data = arg2;
}


SWIGEXPORT void * _wrap_SUNNonlinearSolverContent_Auto__getconvrate_data_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  void *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::getconvrate_data", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (void *) ((arg1)->getconvrate_data);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_to_newt_delay", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->fp_to_newt_delay = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_delay_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_to_newt_delay", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->fp_to_newt_delay);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newt_to_fp_delay", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->newt_to_fp_delay = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_delay_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newt_to_fp_delay", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->newt_to_fp_delay);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__num_solves_since_switch_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::num_solves_since_switch", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->num_solves_since_switch = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__num_solves_since_switch_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::num_solves_since_switch", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->num_solves_since_switch);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_set(SwigClassWrapper const *farg1, double const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  sunrealtype arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newt_to_fp_threshold", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (sunrealtype)(*farg2);
  if (arg1) (arg1)->newt_to_fp_threshold = arg2;
}


SWIGEXPORT double _wrap_SUNNonlinearSolverContent_Auto__newt_to_fp_threshold_get(SwigClassWrapper const *farg1) {
  double fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  sunrealtype result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newt_to_fp_threshold", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (sunrealtype) ((arg1)->newt_to_fp_threshold);
  fresult = (sunrealtype)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_set(SwigClassWrapper const *farg1, double const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  sunrealtype arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_to_newt_threshold", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (sunrealtype)(*farg2);
  if (arg1) (arg1)->fp_to_newt_threshold = arg2;
}


SWIGEXPORT double _wrap_SUNNonlinearSolverContent_Auto__fp_to_newt_threshold_get(SwigClassWrapper const *farg1) {
  double fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  sunrealtype result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_to_newt_threshold", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (sunrealtype) ((arg1)->fp_to_newt_threshold);
  fresult = (sunrealtype)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__num_iters_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::num_iters", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->num_iters = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__num_iters_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::num_iters", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->num_iters);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__num_conv_fails_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::num_conv_fails", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->num_conv_fails = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__num_conv_fails_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::num_conv_fails", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->num_conv_fails);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__switch_count_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::switch_count", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->switch_count = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__switch_count_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::switch_count", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->switch_count);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__fp_num_iters_total_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_num_iters_total", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->fp_num_iters_total = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__fp_num_iters_total_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_num_iters_total", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->fp_num_iters_total);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__newton_num_iters_total_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newton_num_iters_total", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->newton_num_iters_total = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__newton_num_iters_total_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newton_num_iters_total", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->newton_num_iters_total);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_total_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_num_conv_fails_total", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->fp_num_conv_fails_total = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__fp_num_conv_fails_total_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::fp_num_conv_fails_total", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->fp_num_conv_fails_total);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__newton_num_conv_fails_total_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newton_num_conv_fails_total", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->newton_num_conv_fails_total = arg2;
}


SWIGEXPORT long _wrap_SUNNonlinearSolverContent_Auto__newton_num_conv_fails_total_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::newton_num_conv_fails_total", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (long) ((arg1)->newton_num_conv_fails_total);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__auto_ctest_data_set(SwigClassWrapper const *farg1, void *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  void *arg2 = (void *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::auto_ctest_data", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  arg2 = (void *)(farg2);
  if (arg1) (arg1)->auto_ctest_data = arg2;
}


SWIGEXPORT void * _wrap_SUNNonlinearSolverContent_Auto__auto_ctest_data_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  void *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::auto_ctest_data", return 0);
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  result = (void *) ((arg1)->auto_ctest_data);
  fresult = result;
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_SUNNonlinearSolverContent_Auto_() {
  SwigClassWrapper fresult ;
  struct SUNNonlinearSolverContent_Auto_ *result = 0 ;
  
  result = (struct SUNNonlinearSolverContent_Auto_ *)calloc(1, sizeof(struct SUNNonlinearSolverContent_Auto_));
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_SUNNonlinearSolverContent_Auto_(SwigClassWrapper *farg1) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  
  SWIG_check_mutable(*farg1, "struct SUNNonlinearSolverContent_Auto_ *", "SUNNonlinearSolverContent_Auto_", "SUNNonlinearSolverContent_Auto_::~SUNNonlinearSolverContent_Auto_()", return );
  arg1 = (struct SUNNonlinearSolverContent_Auto_ *)(farg1->cptr);
  free((char *) arg1);
}


SWIGEXPORT void _wrap_SUNNonlinearSolverContent_Auto__op_assign__(SwigClassWrapper *farg1, SwigClassWrapper const *farg2) {
  struct SUNNonlinearSolverContent_Auto_ *arg1 = (struct SUNNonlinearSolverContent_Auto_ *) 0 ;
  struct SUNNonlinearSolverContent_Auto_ *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT SUNNonlinearSolver _wrap_FSUNNonlinSol_Auto(N_Vector farg1, int const *farg2, int const *farg3, void *farg4) {
  SUNNonlinearSolver fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNNonlinSolAutoType arg3 ;
  SUNContext arg4 = (SUNContext) 0 ;
  SUNNonlinearSolver result;
  
  arg1 = (N_Vector)(farg1);
  arg2 = (int)(*farg2);
  arg3 = (SUNNonlinSolAutoType)(*farg3);
  arg4 = (SUNContext)(farg4);
  result = (SUNNonlinearSolver)SUNNonlinSol_Auto(arg1,arg2,arg3,arg4);
  fresult = result;
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetType_Auto(SUNNonlinearSolver farg1) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinearSolver_Type result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  result = (SUNNonlinearSolver_Type)SUNNonlinSolGetType_Auto(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolInitialize_Auto(SUNNonlinearSolver farg1) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  result = (SUNErrCode)SUNNonlinSolInitialize_Auto(arg1);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSolve_Auto(SUNNonlinearSolver farg1, N_Vector farg2, N_Vector farg3, N_Vector farg4, double const *farg5, int const *farg6, void *farg7) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  N_Vector arg2 = (N_Vector) 0 ;
  N_Vector arg3 = (N_Vector) 0 ;
  N_Vector arg4 = (N_Vector) 0 ;
  sunrealtype arg5 ;
  int arg6 ;
  void *arg7 = (void *) 0 ;
  int result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (N_Vector)(farg2);
  arg3 = (N_Vector)(farg3);
  arg4 = (N_Vector)(farg4);
  arg5 = (sunrealtype)(*farg5);
  arg6 = (int)(*farg6);
  arg7 = (void *)(farg7);
  result = (int)SUNNonlinSolSolve_Auto(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolFree_Auto(SUNNonlinearSolver farg1) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  result = (SUNErrCode)SUNNonlinSolFree_Auto(arg1);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetSysFns_Auto(SUNNonlinearSolver farg1, SUNNonlinSolSysFn farg2, SUNNonlinSolSysFn farg3) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolSysFn arg2 = (SUNNonlinSolSysFn) 0 ;
  SUNNonlinSolSysFn arg3 = (SUNNonlinSolSysFn) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolSysFn)(farg2);
  arg3 = (SUNNonlinSolSysFn)(farg3);
  result = (SUNErrCode)SUNNonlinSolSetSysFns_Auto(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetConvTestFn_Auto(SUNNonlinearSolver farg1, SUNNonlinSolConvTestFn farg2, void *farg3) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolConvTestFn arg2 = (SUNNonlinSolConvTestFn) 0 ;
  void *arg3 = (void *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolConvTestFn)(farg2);
  arg3 = (void *)(farg3);
  result = (SUNErrCode)SUNNonlinSolSetConvTestFn_Auto(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetLSetupFn_Auto(SUNNonlinearSolver farg1, SUNNonlinSolLSetupFn farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolLSetupFn arg2 = (SUNNonlinSolLSetupFn) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolLSetupFn)(farg2);
  result = (SUNErrCode)SUNNonlinSolSetLSetupFn_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetLSolveFn_Auto(SUNNonlinearSolver farg1, SUNNonlinSolLSolveFn farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolLSolveFn arg2 = (SUNNonlinSolLSolveFn) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolLSolveFn)(farg2);
  result = (SUNErrCode)SUNNonlinSolSetLSolveFn_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetOptions_Auto(SUNNonlinearSolver farg1, SwigArrayWrapper *farg2, SwigArrayWrapper *farg3, int const *farg4, SwigClassWrapper const *farg5) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  char **arg5 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (char *)(farg2->data);
  arg3 = (char *)(farg3->data);
  arg4 = (int)(*farg4);
  SWIG_check_mutable(*farg5, "char **", "SWIGTYPE_p_p_char", "SUNNonlinSolSetOptions_Auto(SUNNonlinearSolver,char const *,char const *,int,char *[])", return 0);
  arg5 = (char **)(farg5->cptr);
  result = (SUNErrCode)SUNNonlinSolSetOptions_Auto(arg1,(char const *)arg2,(char const *)arg3,arg4,arg5);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetNormFn_Auto(SUNNonlinearSolver farg1, SUNNonlinSolNormFn farg2, void *farg3) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolNormFn arg2 = (SUNNonlinSolNormFn) 0 ;
  void *arg3 = (void *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolNormFn)(farg2);
  arg3 = (void *)(farg3);
  result = (SUNErrCode)SUNNonlinSolSetNormFn_Auto(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetMaxIters_Auto(SUNNonlinearSolver farg1, int const *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)SUNNonlinSolSetMaxIters_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetGetConvRateFn_Auto(SUNNonlinearSolver farg1, SUNNonlinSolGetConvRateFn farg2, void *farg3) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolGetConvRateFn arg2 = (SUNNonlinSolGetConvRateFn) 0 ;
  void *arg3 = (void *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolGetConvRateFn)(farg2);
  arg3 = (void *)(farg3);
  result = (SUNErrCode)SUNNonlinSolSetGetConvRateFn_Auto(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetGetUpdateNormFn_Auto(SUNNonlinearSolver farg1, SUNNonlinSolGetUpdateNormFn farg2, void *farg3) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolGetUpdateNormFn arg2 = (SUNNonlinSolGetUpdateNormFn) 0 ;
  void *arg3 = (void *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolGetUpdateNormFn)(farg2);
  arg3 = (void *)(farg3);
  result = (SUNErrCode)SUNNonlinSolSetGetUpdateNormFn_Auto(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolSetSwitchingParameters_Auto(SUNNonlinearSolver farg1, double const *farg2, long const *farg3, double const *farg4, long const *farg5) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  sunrealtype arg2 ;
  long arg3 ;
  sunrealtype arg4 ;
  long arg5 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (sunrealtype)(*farg2);
  arg3 = (long)(*farg3);
  arg4 = (sunrealtype)(*farg4);
  arg5 = (long)(*farg5);
  result = (SUNErrCode)SUNNonlinSolSetSwitchingParameters_Auto(arg1,arg2,arg3,arg4,arg5);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetFixedPointSolver_Auto(SUNNonlinearSolver farg1, void *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinearSolver *arg2 = (SUNNonlinearSolver *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinearSolver *)(farg2);
  result = (SUNErrCode)SUNNonlinSolGetFixedPointSolver_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetNewtonSolver_Auto(SUNNonlinearSolver farg1, void *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinearSolver *arg2 = (SUNNonlinearSolver *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinearSolver *)(farg2);
  result = (SUNErrCode)SUNNonlinSolGetNewtonSolver_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetActiveSolverType_Auto(SUNNonlinearSolver farg1, int *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  SUNNonlinSolAutoType *arg2 = (SUNNonlinSolAutoType *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (SUNNonlinSolAutoType *)(farg2);
  result = (SUNErrCode)SUNNonlinSolGetActiveSolverType_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetSwitchCount_Auto(SUNNonlinearSolver farg1, long *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  long *arg2 = (long *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (long *)(farg2);
  result = (SUNErrCode)SUNNonlinSolGetSwitchCount_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetNumIters_Auto(SUNNonlinearSolver farg1, long *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  long *arg2 = (long *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (long *)(farg2);
  result = (SUNErrCode)SUNNonlinSolGetNumIters_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetTotalNumItersByType_Auto(SUNNonlinearSolver farg1, long *farg2, long *farg3) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  long *arg2 = (long *) 0 ;
  long *arg3 = (long *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (long *)(farg2);
  arg3 = (long *)(farg3);
  result = (SUNErrCode)SUNNonlinSolGetTotalNumItersByType_Auto(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetCurIter_Auto(SUNNonlinearSolver farg1, int *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  int *arg2 = (int *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (int *)(farg2);
  result = (SUNErrCode)SUNNonlinSolGetCurIter_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetNumConvFails_Auto(SUNNonlinearSolver farg1, long *farg2) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  long *arg2 = (long *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (long *)(farg2);
  result = (SUNErrCode)SUNNonlinSolGetNumConvFails_Auto(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNNonlinSolGetTotalNumConvFailsByType_Auto(SUNNonlinearSolver farg1, long *farg2, long *farg3) {
  int fresult ;
  SUNNonlinearSolver arg1 = (SUNNonlinearSolver) 0 ;
  long *arg2 = (long *) 0 ;
  long *arg3 = (long *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNNonlinearSolver)(farg1);
  arg2 = (long *)(farg2);
  arg3 = (long *)(farg3);
  result = (SUNErrCode)SUNNonlinSolGetTotalNumConvFailsByType_Auto(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}



