// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP Rcppsbmod_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
// Rcppcvode
int Rcppcvode(double t, NumericVector IC, NumericVector ydot, double reltolerance, NumericVector abstolerance);
RcppExport SEXP Rcppsbmod_Rcppcvode(SEXP tSEXP, SEXP ICSEXP, SEXP ydotSEXP, SEXP reltoleranceSEXP, SEXP abstoleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IC(ICSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ydot(ydotSEXP);
    Rcpp::traits::input_parameter< double >::type reltolerance(reltoleranceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abstolerance(abstoleranceSEXP);
    __result = Rcpp::wrap(Rcppcvode(t, IC, ydot, reltolerance, abstolerance));
    return __result;
END_RCPP
}
// Rcppcvode_str
int Rcppcvode_str(double t, NumericVector IC, SEXP xpsexp, double reltolerance, NumericVector abstolerance);
RcppExport SEXP Rcppsbmod_Rcppcvode_str(SEXP tSEXP, SEXP ICSEXP, SEXP xpsexpSEXP, SEXP reltoleranceSEXP, SEXP abstoleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type IC(ICSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xpsexp(xpsexpSEXP);
    Rcpp::traits::input_parameter< double >::type reltolerance(reltoleranceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type abstolerance(abstoleranceSEXP);
    __result = Rcpp::wrap(Rcppcvode_str(t, IC, xpsexp, reltolerance, abstolerance));
    return __result;
END_RCPP
}
