# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('Rcppsbmod_rcpp_hello', PACKAGE = 'Rcppsbmod')
}

MassBalances <- function(t, y, ydot) {
    .Call('Rcppsbmod_MassBalances', PACKAGE = 'Rcppsbmod', t, y, ydot)
}

Rcppcvode <- function(t, IC, ydot, reltolerance, abstolerance) {
    .Call('Rcppsbmod_Rcppcvode', PACKAGE = 'Rcppsbmod', t, IC, ydot, reltolerance, abstolerance)
}

timesTwo <- function(x) {
    .Call('Rcppsbmod_timesTwo', PACKAGE = 'Rcppsbmod', x)
}

