# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'cvode
#'
#' CVODE solver to solve stiff ODEs
#'@param time_vec time vector
#'@param IC Initial Conditions
#'@param xpsexp External pointer to RHS function
#'@param reltolerance Relative Tolerance (a scalar)
#'@param abstolerance Absolute Tolerance (a vector with length equal to ydot)
#'@example /inst/examples/cv_Roberts_dns.r
cvode <- function(time_vec, IC, xpsexp, reltolerance, abstolerance) {
    .Call('_sundialr_cvode', PACKAGE = 'sundialr', time_vec, IC, xpsexp, reltolerance, abstolerance)
}

